// Eksempelnettsider for demo-galleriet. ALLE bedriftene er oppdiktet.
// Innholdet i selve demoene er på norsk (kundene er norske bedrifter);
// bare bransjenavnene har engelsk oversettelse.

export type DemoGroup = "beauty" | "health" | "food" | "trades" | "services" | "retail";

export const demoGroups: { key: DemoGroup; no: string; en: string }[] = [
  { key: "beauty", no: "Skjønnhet", en: "Beauty" },
  { key: "health", no: "Helse og trening", en: "Health and fitness" },
  { key: "food", no: "Mat og drikke", en: "Food and drink" },
  { key: "trades", no: "Håndverk", en: "Trades" },
  { key: "services", no: "Tjenester", en: "Services" },
  { key: "retail", no: "Butikk", en: "Retail" },
];

export type DemoTheme = {
  bg: string; // sidebakgrunn
  fg: string; // tekst
  muted: string; // dempet tekst
  primary: string; // knapper og flater
  onPrimary: string; // tekst på primary
  soft: string; // kort og seksjoner
  accent: string; // detaljer
};

export type Demo = {
  slug: string;
  group: DemoGroup;
  label: { no: string; en: string };
  name: string;
  tagline: string;
  title: string;
  text: string;
  cta: string;
  services: { name: string; price: string }[];
  about: string;
  hours: string[];
  layout: "split" | "center" | "bold";
  font: "serif" | "sans";
  theme: DemoTheme;
};

// Paletter som gjenbrukes, så demoene ser gjennomarbeidet ut.
const t = {
  blush: { bg: "#FBF6F3", fg: "#2B1E1C", muted: "#6E5A55", primary: "#AA5F4A", onPrimary: "#FFFFFF", soft: "#F3E7E1", accent: "#D9A48F" },
  charcoal: { bg: "#F4F2EE", fg: "#1A1A1A", muted: "#555555", primary: "#1A1A1A", onPrimary: "#F4F2EE", soft: "#E7E3DC", accent: "#B08D57" },
  lilac: { bg: "#F8F6FB", fg: "#27213A", muted: "#5F5873", primary: "#6D5BA8", onPrimary: "#FFFFFF", soft: "#ECE7F6", accent: "#B7A8E0" },
  sage: { bg: "#F5F7F2", fg: "#1F2A22", muted: "#566257", primary: "#4E6B53", onPrimary: "#FFFFFF", soft: "#E5ECE1", accent: "#A7BFA2" },
  sand: { bg: "#FAF6EF", fg: "#2A2419", muted: "#6B604D", primary: "#926B37", onPrimary: "#FFFFFF", soft: "#F0E6D5", accent: "#D6B98A" },
  clinic: { bg: "#F4F8FB", fg: "#0F2536", muted: "#4A6072", primary: "#1F6FA8", onPrimary: "#FFFFFF", soft: "#E3EEF6", accent: "#8CC0E3" },
  teal: { bg: "#F2F8F7", fg: "#0E2A28", muted: "#4B6461", primary: "#1E7A70", onPrimary: "#FFFFFF", soft: "#DDEEEB", accent: "#7FC4BA" },
  energy: { bg: "#111315", fg: "#F5F5F2", muted: "#B4B7B2", primary: "#D8F24A", onPrimary: "#111315", soft: "#1D2124", accent: "#D8F24A" },
  espresso: { bg: "#F7F1EA", fg: "#2A1C14", muted: "#6D5647", primary: "#5B3A26", onPrimary: "#F7F1EA", soft: "#EEE2D3", accent: "#C58B5C" },
  bistro: { bg: "#14171A", fg: "#F3EEE6", muted: "#B9B1A5", primary: "#BE513A", onPrimary: "#FFFFFF", soft: "#1F2327", accent: "#E0A458" },
  tomato: { bg: "#FFF8F1", fg: "#2A1510", muted: "#6E4E44", primary: "#C0392B", onPrimary: "#FFFFFF", soft: "#FBE7D6", accent: "#2E7D32" },
  volt: { bg: "#F5F6F8", fg: "#10151C", muted: "#4D5663", primary: "#F2B705", onPrimary: "#10151C", soft: "#E6E9EE", accent: "#10151C" },
  water: { bg: "#F3F7FC", fg: "#0C1F33", muted: "#48607A", primary: "#0B5CAD", onPrimary: "#FFFFFF", soft: "#E1ECF8", accent: "#5AA2E6" },
  timber: { bg: "#F7F3EC", fg: "#241C12", muted: "#65584A", primary: "#6B4F2A", onPrimary: "#FFFFFF", soft: "#ECE3D4", accent: "#B8894B" },
  paint: { bg: "#FBFAF7", fg: "#1D2433", muted: "#596276", primary: "#B75831", onPrimary: "#FFFFFF", soft: "#F1EEE7", accent: "#2F5D8A" },
  slate: { bg: "#F2F4F6", fg: "#161C24", muted: "#505B69", primary: "#2F3B4A", onPrimary: "#FFFFFF", soft: "#E1E6EB", accent: "#C0392B" },
  garden: { bg: "#F4F7EF", fg: "#1B2614", muted: "#56634B", primary: "#3F6B2A", onPrimary: "#FFFFFF", soft: "#E3EBD6", accent: "#9BBE5C" },
  brick: { bg: "#F8F4F1", fg: "#271915", muted: "#6A534B", primary: "#9C3D2C", onPrimary: "#FFFFFF", soft: "#EFE3DD", accent: "#C98A6D" },
  finance: { bg: "#F5F6F9", fg: "#0E1A2B", muted: "#4E5A6B", primary: "#0E2A4F", onPrimary: "#FFFFFF", soft: "#E4E8EF", accent: "#3A7BD5" },
  law: { bg: "#F7F5F0", fg: "#1C1A16", muted: "#5D584E", primary: "#2D2A24", onPrimary: "#F7F5F0", soft: "#ECE8DE", accent: "#9C7A3C" },
  mono: { bg: "#FFFFFF", fg: "#111111", muted: "#5A5A5A", primary: "#111111", onPrimary: "#FFFFFF", soft: "#F1F1F1", accent: "#111111" },
  fresh: { bg: "#F3FAF8", fg: "#0F2622", muted: "#4A6660", primary: "#12816D", onPrimary: "#FFFFFF", soft: "#DDF1EC", accent: "#7FD1BE" },
  garage: { bg: "#15181C", fg: "#F2F2F2", muted: "#A9AEB5", primary: "#C64C28", onPrimary: "#FFFFFF", soft: "#20252B", accent: "#E4572E" },
  road: { bg: "#F6F7F9", fg: "#121821", muted: "#525D6B", primary: "#2B59C3", onPrimary: "#FFFFFF", soft: "#E4E9F3", accent: "#F4B400" },
  flower: { bg: "#FDF7F8", fg: "#2A1A20", muted: "#6D5660", primary: "#A63D5E", onPrimary: "#FFFFFF", soft: "#F6E3E8", accent: "#6F9A5B" },
  boutique: { bg: "#F6F3EF", fg: "#1E1B18", muted: "#625B53", primary: "#1E1B18", onPrimary: "#F6F3EF", soft: "#EBE5DD", accent: "#A8876A" },
} satisfies Record<string, DemoTheme>;

const hoursWeek = ["Man–fre 09–17", "Lør 10–15", "Søn stengt"];
const hoursShop = ["Man–fre 10–18", "Lør 10–16", "Søn stengt"];
const hoursCraft = ["Man–fre 07–15", "Akutt: etter avtale"];

export const demos: Demo[] = [
  // ---------------------------------------------------------------- Skjønnhet
  {
    slug: "frisor",
    group: "beauty",
    label: { no: "Frisør", en: "Hair salon" },
    name: "Salong Lykke",
    tagline: "Frisør i sentrum",
    title: "Hår som får deg til å føle deg som deg.",
    text: "Klipp, farge og styling i rolige omgivelser. Book time på nett – det tar under ett minutt.",
    cta: "Book time",
    services: [
      { name: "Dameklipp", price: "fra 690 kr" },
      { name: "Herreklipp", price: "fra 490 kr" },
      { name: "Farge og striper", price: "fra 1 290 kr" },
      { name: "Oppsett og styling", price: "fra 850 kr" },
    ],
    about: "Tre frisører med lang erfaring og en felles lidenskap for sunt hår og gode samtaler.",
    hours: ["Tir–fre 09–18", "Lør 09–15", "Søn–man stengt"],
    layout: "split",
    font: "serif",
    theme: t.blush,
  },
  {
    slug: "barber",
    group: "beauty",
    label: { no: "Barbershop", en: "Barbershop" },
    name: "Nord Barbers",
    tagline: "Barbershop",
    title: "Skarpe kutt. Rolig stemning.",
    text: "Klassiske og moderne herreklipp, skjeggtrim og barbering med varm kniv.",
    cta: "Book stol",
    services: [
      { name: "Herreklipp", price: "450 kr" },
      { name: "Skjeggtrim", price: "300 kr" },
      { name: "Klipp og skjegg", price: "650 kr" },
      { name: "Barbering med varm kniv", price: "400 kr" },
    ],
    about: "Drop-in når vi har ledig, ellers book stol på nett. Kaffen står klar.",
    hours: ["Man–fre 10–19", "Lør 10–16", "Søn stengt"],
    layout: "bold",
    font: "sans",
    theme: t.charcoal,
  },
  {
    slug: "neglsalong",
    group: "beauty",
    label: { no: "Neglsalong", en: "Nail salon" },
    name: "Studio Pastell",
    tagline: "Negler og vipper",
    title: "Små detaljer som gjør en stor forskjell.",
    text: "Gelé, forlengelse, nail art og vippeløft – med hygiene og holdbarhet i fokus.",
    cta: "Book behandling",
    services: [
      { name: "Gelélakk hender", price: "590 kr" },
      { name: "Forlengelse", price: "fra 890 kr" },
      { name: "Nail art", price: "fra 100 kr" },
      { name: "Vippeløft", price: "650 kr" },
    ],
    about: "En liten salong med stor oppmerksomhet på detaljer. Vi steriliserer alt utstyr mellom hver kunde.",
    hours: hoursShop,
    layout: "center",
    font: "serif",
    theme: t.lilac,
  },
  {
    slug: "hudpleie",
    group: "beauty",
    label: { no: "Hudpleie", en: "Skincare" },
    name: "Hudklinikken Aura",
    tagline: "Hudpleie og ansiktsbehandlinger",
    title: "Frisk hud begynner med riktig behandling.",
    text: "Personlig hudanalyse og behandlinger tilpasset din hudtype – fra dyprens til kjemisk peeling.",
    cta: "Book hudanalyse",
    services: [
      { name: "Hudanalyse", price: "450 kr" },
      { name: "Dyprens ansikt", price: "990 kr" },
      { name: "Kjemisk peeling", price: "fra 1 190 kr" },
      { name: "Microneedling", price: "fra 1 890 kr" },
    ],
    about: "Utdannede hudterapeuter som tar seg tid til å forstå huden din før vi anbefaler noe.",
    hours: hoursWeek,
    layout: "split",
    font: "serif",
    theme: t.sage,
  },
  {
    slug: "massasje",
    group: "beauty",
    label: { no: "Massasje", en: "Massage" },
    name: "Ro Massasje",
    tagline: "Massasje og velvære",
    title: "En time for deg selv.",
    text: "Klassisk massasje, idrettsmassasje og hot stone – for kropp som trenger ro.",
    cta: "Book massasje",
    services: [
      { name: "Klassisk massasje 60 min", price: "890 kr" },
      { name: "Idrettsmassasje 60 min", price: "950 kr" },
      { name: "Hot stone 75 min", price: "1 150 kr" },
      { name: "Gavekort", price: "valgfritt beløp" },
    ],
    about: "Autoriserte massører i rolige behandlingsrom. Kom som du er, gå avslappet.",
    hours: ["Man–fre 10–20", "Lør 10–16", "Søn stengt"],
    layout: "center",
    font: "serif",
    theme: t.sand,
  },

  // ------------------------------------------------------------ Helse og trening
  {
    slug: "tannlege",
    group: "health",
    label: { no: "Tannlege", en: "Dentist" },
    name: "Smil Tannklinikk",
    tagline: "Tannlege og tannpleie",
    title: "Trygg tannbehandling – også for deg som gruer deg.",
    text: "Undersøkelse, rens, fyllinger og estetisk behandling. Nye pasienter er velkomne.",
    cta: "Bestill time",
    services: [
      { name: "Undersøkelse og røntgen", price: "fra 890 kr" },
      { name: "Tannrens", price: "fra 690 kr" },
      { name: "Fylling", price: "fra 1 150 kr" },
      { name: "Tannbleking", price: "fra 3 500 kr" },
    ],
    about: "Tannleger og tannpleiere som forklarer hva de gjør, og aldri har det travelt med deg i stolen.",
    hours: ["Man–fre 08–16", "Tor 08–19"],
    layout: "split",
    font: "sans",
    theme: t.clinic,
  },
  {
    slug: "fysioterapeut",
    group: "health",
    label: { no: "Fysioterapeut", en: "Physiotherapist" },
    name: "Bevegelse Fysio",
    tagline: "Fysioterapi og rehabilitering",
    title: "Tilbake til det du liker å gjøre.",
    text: "Undersøkelse, behandling og treningsopplegg for smerter, skader og rehabilitering.",
    cta: "Bestill time",
    services: [
      { name: "Førstegangskonsultasjon", price: "750 kr" },
      { name: "Oppfølgingstime", price: "590 kr" },
      { name: "Idrettsskade", price: "fra 590 kr" },
      { name: "Treningsveiledning", price: "650 kr" },
    ],
    about: "Fysioterapeuter med bred erfaring fra idrett, rygg og nakke. Vi finner årsaken, ikke bare symptomet.",
    hours: ["Man–fre 07–19"],
    layout: "center",
    font: "sans",
    theme: t.teal,
  },
  {
    slug: "veterinaer",
    group: "health",
    label: { no: "Veterinær", en: "Veterinarian" },
    name: "Poter Dyreklinikk",
    tagline: "Veterinær for hund og katt",
    title: "Omsorg for de som betyr mest.",
    text: "Vaksiner, helsesjekk, tannbehandling og akutt hjelp for hund, katt og smådyr.",
    cta: "Bestill time",
    services: [
      { name: "Helsesjekk og vaksine", price: "fra 790 kr" },
      { name: "Konsultasjon", price: "fra 650 kr" },
      { name: "Tannrens", price: "fra 2 400 kr" },
      { name: "Kastrering", price: "fra 2 900 kr" },
    ],
    about: "Veterinærer og dyrepleiere som tar seg tid – både til dyret og til deg.",
    hours: ["Man–fre 08–18", "Lør 10–14"],
    layout: "split",
    font: "sans",
    theme: t.sage,
  },
  {
    slug: "treningssenter",
    group: "health",
    label: { no: "Treningssenter / PT", en: "Gym / PT" },
    name: "Kraft Studio",
    tagline: "Trening og personlig trener",
    title: "Sterkere. Hver uke.",
    text: "Små grupper, personlig trener og et program som faktisk passer deg.",
    cta: "Prøv gratis time",
    services: [
      { name: "Medlemskap", price: "549 kr/mnd" },
      { name: "PT-time", price: "750 kr" },
      { name: "Småtrening (4 pers.)", price: "290 kr" },
      { name: "Oppstartspakke", price: "1 490 kr" },
    ],
    about: "Et lite senter med store ambisjoner for deg. Ingen køer ved stativet.",
    hours: ["Alle dager 05–23"],
    layout: "bold",
    font: "sans",
    theme: t.energy,
  },
  {
    slug: "yoga",
    group: "health",
    label: { no: "Yoga", en: "Yoga studio" },
    name: "Pust Yoga",
    tagline: "Yoga og meditasjon",
    title: "Finn roen, ett pust om gangen.",
    text: "Timer for nybegynnere og viderekomne – vinyasa, yin og meditasjon.",
    cta: "Se timeplan",
    services: [
      { name: "Drop-in", price: "220 kr" },
      { name: "Klippekort 10", price: "1 900 kr" },
      { name: "Månedskort", price: "790 kr" },
      { name: "Nybegynnerkurs", price: "1 200 kr" },
    ],
    about: "Et lyst og stille studio der alle er velkomne, uansett erfaring.",
    hours: ["Man–fre 07–21", "Lør–søn 09–13"],
    layout: "center",
    font: "serif",
    theme: t.sand,
  },

  // -------------------------------------------------------------- Mat og drikke
  {
    slug: "kafe",
    group: "food",
    label: { no: "Kafé", en: "Café" },
    name: "Kaffebrenneriet Hav",
    tagline: "Kaffebar og bakst",
    title: "God kaffe. Ingen hast.",
    text: "Nybrent kaffe, hjemmebakst og lunsj laget fra bunnen hver dag.",
    cta: "Se menyen",
    services: [
      { name: "Cappuccino", price: "52 kr" },
      { name: "Kanelbolle", price: "45 kr" },
      { name: "Dagens suppe", price: "129 kr" },
      { name: "Surdeigsmacka", price: "119 kr" },
    ],
    about: "Vi brenner vår egen kaffe og baker alt selv. Sett deg ned – vi tar bestillingen ved bordet.",
    hours: ["Man–fre 07–17", "Lør–søn 09–17"],
    layout: "split",
    font: "serif",
    theme: t.espresso,
  },
  {
    slug: "restaurant",
    group: "food",
    label: { no: "Restaurant", en: "Restaurant" },
    name: "Brygga Bistro",
    tagline: "Bistro ved sjøen",
    title: "Sesongens beste, rett fra kjøkkenet.",
    text: "Lokale råvarer, en meny som skifter med sesongen og vin valgt med omhu.",
    cta: "Bestill bord",
    services: [
      { name: "Treretters meny", price: "695 kr" },
      { name: "Dagens fisk", price: "345 kr" },
      { name: "Vinpakke", price: "450 kr" },
      { name: "Selskap og catering", price: "på forespørsel" },
    ],
    about: "Et lite kjøkken med store smaker. Vi lager det meste fra bunnen, hver dag.",
    hours: ["Tir–lør 16–23", "Søn 14–21", "Man stengt"],
    layout: "bold",
    font: "serif",
    theme: t.bistro,
  },
  {
    slug: "bakeri",
    group: "food",
    label: { no: "Bakeri", en: "Bakery" },
    name: "Morgenbrød Bakeri",
    tagline: "Håndverksbakeri",
    title: "Nybakt hver morgen, siden klokka fire.",
    text: "Surdeigsbrød, wienerbrød og kaker bakt for hånd med gode råvarer.",
    cta: "Bestill kake",
    services: [
      { name: "Surdeigsbrød", price: "69 kr" },
      { name: "Skolebolle", price: "39 kr" },
      { name: "Bløtkake (12 pers.)", price: "fra 590 kr" },
      { name: "Frokostkurv", price: "fra 399 kr" },
    ],
    about: "Vi baker alt i butikken, med lang hevetid og uten snarveier.",
    hours: ["Man–fre 07–17", "Lør 08–15", "Søn stengt"],
    layout: "center",
    font: "serif",
    theme: t.sand,
  },
  {
    slug: "pizzeria",
    group: "food",
    label: { no: "Pizzeria", en: "Pizzeria" },
    name: "Forno Pizzeria",
    tagline: "Steinovnsbakt pizza",
    title: "Napolitansk pizza, rett fra steinovnen.",
    text: "Deig som hever i 48 timer, italienske råvarer og 90 sekunder i ovnen.",
    cta: "Bestill takeaway",
    services: [
      { name: "Margherita", price: "179 kr" },
      { name: "Diavola", price: "199 kr" },
      { name: "Tartufo", price: "229 kr" },
      { name: "Tiramisu", price: "89 kr" },
    ],
    about: "Et familiedrevet pizzeria med én regel: aldri snarveier med deigen.",
    hours: ["Alle dager 14–22"],
    layout: "split",
    font: "sans",
    theme: t.tomato,
  },
  {
    slug: "catering",
    group: "food",
    label: { no: "Catering", en: "Catering" },
    name: "Fest og Fat Catering",
    tagline: "Catering for firma og selskap",
    title: "Maten er klar. Du kan nyte selskapet.",
    text: "Lunsj til møter, tapas til fest og buffet til store anledninger – levert og ferdig anrettet.",
    cta: "Be om tilbud",
    services: [
      { name: "Møtelunsj", price: "fra 189 kr/pers." },
      { name: "Tapasbord", price: "fra 329 kr/pers." },
      { name: "Festbuffet", price: "fra 449 kr/pers." },
      { name: "Servering", price: "på forespørsel" },
    ],
    about: "Vi lager maten, leverer den og rydder etterpå. Du trenger bare å dukke opp.",
    hours: hoursWeek,
    layout: "center",
    font: "sans",
    theme: t.brick,
  },

  // ----------------------------------------------------------------- Håndverk
  {
    slug: "elektriker",
    group: "trades",
    label: { no: "Elektriker", en: "Electrician" },
    name: "Lynrask Elektro",
    tagline: "Autorisert elektriker",
    title: "Strømmen på plass. Første gang.",
    text: "Installasjon, feilsøking, elbillader og smarthus – for privat og bedrift.",
    cta: "Få gratis befaring",
    services: [
      { name: "Elbillader montert", price: "fra 12 900 kr" },
      { name: "Nytt sikringsskap", price: "fra 18 500 kr" },
      { name: "Feilsøking", price: "fra 990 kr" },
      { name: "Smarthus", price: "på forespørsel" },
    ],
    about: "Autoriserte elektrikere som møter opp når vi sier, og rydder etter oss.",
    hours: hoursCraft,
    layout: "bold",
    font: "sans",
    theme: t.volt,
  },
  {
    slug: "rorlegger",
    group: "trades",
    label: { no: "Rørlegger", en: "Plumber" },
    name: "Rørteknikk Vest",
    tagline: "Rørlegger",
    title: "Lekkasje? Vi er på vei.",
    text: "Bad, kjøkken, varmtvannsbereder og akutt lekkasje – med fast pris på vanlige jobber.",
    cta: "Ring oss",
    services: [
      { name: "Ny varmtvannsbereder", price: "fra 14 900 kr" },
      { name: "Nytt toalett", price: "fra 6 900 kr" },
      { name: "Akutt lekkasje", price: "fra 1 490 kr" },
      { name: "Totalrenovering bad", price: "på forespørsel" },
    ],
    about: "Godkjente rørleggere med våtromssertifikat. Vi gir deg prisen før vi starter.",
    hours: ["Man–fre 07–16", "Døgnvakt ved akutt lekkasje"],
    layout: "split",
    font: "sans",
    theme: t.water,
  },
  {
    slug: "tomrer",
    group: "trades",
    label: { no: "Tømrer / snekker", en: "Carpenter" },
    name: "Laftet Bygg",
    tagline: "Tømrer og snekker",
    title: "Solid håndverk som varer.",
    text: "Tilbygg, terrasse, vinduer og kjøkken – fra tegning til ferdig jobb.",
    cta: "Be om befaring",
    services: [
      { name: "Terrasse", price: "fra 1 900 kr/m²" },
      { name: "Vindusbytte", price: "fra 9 900 kr" },
      { name: "Kjøkkenmontering", price: "fra 14 900 kr" },
      { name: "Tilbygg", price: "på forespørsel" },
    ],
    about: "Et lite snekkerfirma med store krav til kvalitet. Alle jobber gjøres av egne fagfolk.",
    hours: hoursCraft,
    layout: "split",
    font: "serif",
    theme: t.timber,
  },
  {
    slug: "maler",
    group: "trades",
    label: { no: "Maler", en: "Painter" },
    name: "Fargerik Maling",
    tagline: "Malermester",
    title: "Ferdig malt, uten flekker.",
    text: "Innvendig og utvendig maling, tapetsering og sparkling – ryddig fra start til slutt.",
    cta: "Få pris",
    services: [
      { name: "Maling av rom", price: "fra 4 900 kr" },
      { name: "Utvendig husmaling", price: "på forespørsel" },
      { name: "Tapetsering", price: "fra 3 900 kr" },
      { name: "Fargerådgivning", price: "gratis" },
    ],
    about: "Malere som dekker til, maler presist og rydder etter seg.",
    hours: hoursCraft,
    layout: "center",
    font: "sans",
    theme: t.paint,
  },
  {
    slug: "taktekker",
    group: "trades",
    label: { no: "Taktekker", en: "Roofer" },
    name: "Tett Tak",
    tagline: "Taktekking og takrenner",
    title: "Et tak du slipper å tenke på.",
    text: "Nytt tak, reparasjon, takrenner og inspeksjon – med garanti på arbeidet.",
    cta: "Få gratis befaring",
    services: [
      { name: "Takinspeksjon", price: "1 490 kr" },
      { name: "Reparasjon", price: "fra 3 900 kr" },
      { name: "Nye takrenner", price: "fra 9 500 kr" },
      { name: "Nytt tak", price: "på forespørsel" },
    ],
    about: "Taktekkere med lang erfaring fra kystvær. Vi dokumenterer jobben med bilder.",
    hours: hoursCraft,
    layout: "bold",
    font: "sans",
    theme: t.slate,
  },
  {
    slug: "anleggsgartner",
    group: "trades",
    label: { no: "Anleggsgartner", en: "Landscaper" },
    name: "Grønn Hage",
    tagline: "Anleggsgartner",
    title: "Hagen du har drømt om.",
    text: "Belegningsstein, plen, beplantning og støttemurer – planlagt og bygget for deg.",
    cta: "Be om befaring",
    services: [
      { name: "Belegningsstein", price: "fra 1 450 kr/m²" },
      { name: "Ferdigplen", price: "fra 290 kr/m²" },
      { name: "Hageplanlegging", price: "fra 2 900 kr" },
      { name: "Hagestell", price: "fra 690 kr/t" },
    ],
    about: "Anleggsgartnere som elsker det de driver med – og det synes i hagen din.",
    hours: ["Man–fre 07–16 (april–november)"],
    layout: "split",
    font: "serif",
    theme: t.garden,
  },
  {
    slug: "murer",
    group: "trades",
    label: { no: "Murer", en: "Mason" },
    name: "Mur og Flis",
    tagline: "Murer og flislegger",
    title: "Flis og mur, lagt med presisjon.",
    text: "Flislegging av bad, pipe, grunnmur og peis – med våtromssertifikat.",
    cta: "Få pris",
    services: [
      { name: "Flislegging bad", price: "fra 890 kr/m²" },
      { name: "Pipehatt og pusse pipe", price: "fra 7 900 kr" },
      { name: "Grunnmursreparasjon", price: "på forespørsel" },
      { name: "Peismontering", price: "fra 12 900 kr" },
    ],
    about: "Murere og flisleggere med øye for detaljer. Rette fuger, hver gang.",
    hours: hoursCraft,
    layout: "center",
    font: "sans",
    theme: t.brick,
  },

  // ---------------------------------------------------------------- Tjenester
  {
    slug: "regnskap",
    group: "services",
    label: { no: "Regnskapsfører", en: "Accountant" },
    name: "Balanse Regnskap",
    tagline: "Autorisert regnskapsfører",
    title: "Regnskapet i orden. Hodet ditt fritt.",
    text: "Bokføring, lønn, MVA og årsoppgjør for små og mellomstore bedrifter.",
    cta: "Book en prat",
    services: [
      { name: "Bokføring", price: "fra 1 490 kr/mnd" },
      { name: "Lønn", price: "fra 290 kr/ansatt" },
      { name: "Årsoppgjør", price: "fra 7 900 kr" },
      { name: "Oppstartshjelp", price: "gratis første time" },
    ],
    about: "Autoriserte regnskapsførere som svarer på e-post samme dag og forklarer på godt norsk.",
    hours: ["Man–fre 08–16"],
    layout: "split",
    font: "sans",
    theme: t.finance,
  },
  {
    slug: "advokat",
    group: "services",
    label: { no: "Advokat", en: "Lawyer" },
    name: "Holm og Dahl Advokater",
    tagline: "Advokatfirma",
    title: "Tydelige råd når det gjelder.",
    text: "Arbeidsrett, kontrakter, eiendom og familie – for privatpersoner og bedrifter.",
    cta: "Bestill konsultasjon",
    services: [
      { name: "Første samtale", price: "30 min gratis" },
      { name: "Kontraktsgjennomgang", price: "fra 3 900 kr" },
      { name: "Arbeidsrett", price: "timepris" },
      { name: "Arv og skifte", price: "timepris" },
    ],
    about: "Advokater som gir deg svaret rett ut – og forklarer hva det betyr for deg.",
    hours: ["Man–fre 08–17"],
    layout: "bold",
    font: "serif",
    theme: t.law,
  },
  {
    slug: "fotograf",
    group: "services",
    label: { no: "Fotograf", en: "Photographer" },
    name: "Lys Fotostudio",
    tagline: "Fotograf",
    title: "Bilder som forteller historien din.",
    text: "Portrett, bryllup, bedrift og produkt – i studio eller på stedet.",
    cta: "Book fotografering",
    services: [
      { name: "Portrett", price: "fra 2 490 kr" },
      { name: "Bedriftsportretter", price: "fra 3 900 kr" },
      { name: "Bryllup", price: "fra 14 900 kr" },
      { name: "Produktbilder", price: "fra 490 kr/bilde" },
    ],
    about: "En fotograf med øye for lys og mennesker. Du får bildene innen to uker.",
    hours: ["Etter avtale"],
    layout: "center",
    font: "serif",
    theme: t.mono,
  },
  {
    slug: "renhold",
    group: "services",
    label: { no: "Renhold", en: "Cleaning" },
    name: "Skinn Renhold",
    tagline: "Renhold for hjem og bedrift",
    title: "Kom hjem til et rent hus.",
    text: "Fast vask, flyttevask, vindusvask og kontorrenhold – med godkjent renholdsbedrift.",
    cta: "Få pris",
    services: [
      { name: "Fast vask", price: "fra 590 kr/gang" },
      { name: "Flyttevask", price: "fra 3 490 kr" },
      { name: "Vindusvask", price: "fra 990 kr" },
      { name: "Kontorrenhold", price: "på forespørsel" },
    ],
    about: "Godkjent renholdsvirksomhet med faste renholdere du blir kjent med.",
    hours: ["Man–lør 07–20"],
    layout: "split",
    font: "sans",
    theme: t.fresh,
  },
  {
    slug: "bilverksted",
    group: "services",
    label: { no: "Bilverksted", en: "Car repair" },
    name: "Motorgarasjen",
    tagline: "Bilverksted og EU-kontroll",
    title: "Bilen i trygge hender.",
    text: "Service, EU-kontroll, dekkskift og reparasjoner på alle bilmerker – også elbil.",
    cta: "Bestill time",
    services: [
      { name: "EU-kontroll", price: "890 kr" },
      { name: "Service", price: "fra 2 490 kr" },
      { name: "Dekkskift", price: "590 kr" },
      { name: "Elbilservice", price: "fra 1 990 kr" },
    ],
    about: "Mekanikere som forklarer hva som må gjøres – og hva som kan vente.",
    hours: ["Man–fre 07–16"],
    layout: "bold",
    font: "sans",
    theme: t.garage,
  },
  {
    slug: "trafikkskole",
    group: "services",
    label: { no: "Trafikkskole", en: "Driving school" },
    name: "Grønt Lys Trafikkskole",
    tagline: "Trafikkskole",
    title: "Førerkortet, uten stress.",
    text: "Trafikalt grunnkurs, kjøretimer og oppkjøring for klasse B og BE.",
    cta: "Meld deg på",
    services: [
      { name: "Trafikalt grunnkurs", price: "3 200 kr" },
      { name: "Kjøretime (45 min)", price: "790 kr" },
      { name: "Sikkerhetskurs bane", price: "4 900 kr" },
      { name: "Oppkjøringspakke", price: "2 900 kr" },
    ],
    about: "Tålmodige lærere og moderne biler. Vi øver til du er trygg – ikke bare til prøven.",
    hours: ["Man–fre 08–20", "Lør 09–15"],
    layout: "center",
    font: "sans",
    theme: t.road,
  },

  // ------------------------------------------------------------------- Butikk
  {
    slug: "blomsterbutikk",
    group: "retail",
    label: { no: "Blomsterbutikk", en: "Florist" },
    name: "Blomsterhagen",
    tagline: "Blomsterbutikk",
    title: "Blomster for hver anledning.",
    text: "Buketter, bryllup, begravelse og planter – levert på døren samme dag.",
    cta: "Bestill bukett",
    services: [
      { name: "Sesongbukett", price: "fra 395 kr" },
      { name: "Brudebukett", price: "fra 1 490 kr" },
      { name: "Sørgebinderi", price: "fra 890 kr" },
      { name: "Levering", price: "fra 149 kr" },
    ],
    about: "Floristene våre binder hver bukett for hånd, med blomster som holder lenge.",
    hours: hoursShop,
    layout: "split",
    font: "serif",
    theme: t.flower,
  },
  {
    slug: "klesbutikk",
    group: "retail",
    label: { no: "Klesbutikk", en: "Clothing store" },
    name: "Atelier Nord",
    tagline: "Klær og tilbehør",
    title: "Tidløse klær, laget for å brukes.",
    text: "Nøye utvalgte merker i naturlige materialer – for hverdag og fest.",
    cta: "Se kolleksjonen",
    services: [
      { name: "Ullgensere", price: "fra 1 299 kr" },
      { name: "Kåper og jakker", price: "fra 2 499 kr" },
      { name: "Skjorter", price: "fra 899 kr" },
      { name: "Personlig styling", price: "gratis i butikk" },
    ],
    about: "En liten butikk med få, gode plagg – og tid til å hjelpe deg finne riktig størrelse.",
    hours: hoursShop,
    layout: "bold",
    font: "serif",
    theme: t.boutique,
  },
];

export function getDemo(slug: string) {
  return demos.find((d) => d.slug === slug);
}
